### ISSUE TITLE
Suggestion: Improve arrow angle.

### ISSUE THREAD

**Issue by kevinsmia1939** [timvdm/Molsketch#4]
Currently, the arrow look like the drawing on the top.
I propose to consider to change it to look like the one below.
This image is recreate in inkscape.
![bitmap](https://user-images.githubusercontent.com/11407922/172260713-e5182364-5c14-43de-bd24-665253238646.jpg)

**Comment by hvennekate** [comment]
Please take a look at https://github.com/hvennekate/Molsketch or http://molsketch.sourceforge.net/ for the latest version. You can move the bezier support points in order to achieve precisely what you are proposing.
